//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VamTech.Ecommerce.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VamTech.Ecommerce.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algunas propiedades no son válidas.
        /// </summary>
        internal static string Bad_Request_Some {
            get {
                return ResourceManager.GetString("Bad Request Some", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Bienvenido a {0}&lt;/h1&gt;&lt;br&gt;
        /// &lt;p&gt;Por favor confirma tu mail  &lt;a href=&apos;{1}&apos;&gt;Haciendo clic aquí&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string Confirm_your_email_body {
            get {
                return ResourceManager.GetString("Confirm your email body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma tu email.
        /// </summary>
        internal static string Confirm_your_email_subject {
            get {
                return ResourceManager.GetString("Confirm your email subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmado exitosamente!.
        /// </summary>
        internal static string Email_confirmed_successfully {
            get {
                return ResourceManager.GetString("Email confirmed successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email no pudo confirmarse.
        /// </summary>
        internal static string Email_did_not_confirm {
            get {
                return ResourceManager.GetString("Email did not confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password incorrecto.
        /// </summary>
        internal static string Invalid_Password {
            get {
                return ResourceManager.GetString("Invalid Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt; ¡Hola! Se ha notado un nuevo inicio de sesión en su cuenta &lt;/h1&gt; &lt;p&gt; Nuevo inicio de sesión en su cuenta en {0} &lt;/p&gt;.
        /// </summary>
        internal static string New_login_Body {
            get {
                return ResourceManager.GetString("New login Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo login.
        /// </summary>
        internal static string New_login_subject {
            get {
                return ResourceManager.GetString("New login subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cliente el usuario asociado con el email.
        /// </summary>
        internal static string No_cliente_associated_with_email {
            get {
                return ResourceManager.GetString("No cliente associated with email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el usuario asociado con el email.
        /// </summary>
        internal static string No_user_associated_with_email {
            get {
                return ResourceManager.GetString("No user associated with email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña no coincide con su confirmacion.
        /// </summary>
        internal static string Password_doesn_t_match_its_confirmation {
            get {
                return ResourceManager.GetString("Password doesn\'t match its confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña fue reseteada correctamente.
        /// </summary>
        internal static string Password_has_been_reset_successfully {
            get {
                return ResourceManager.GetString("Password has been reset successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Producto&lt;/td&gt;
        ///    &lt;td&gt;Precio Unitario&lt;/td&gt;
        ///    &lt;td&gt;Cantidad&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///     {0}
        ///  &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string PO_Body_Detail {
            get {
                return ResourceManager.GetString("PO Body Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Producto&lt;/td&gt;
        ///    &lt;td&gt;Descuento&lt;/td&gt;
        ///    &lt;td&gt;Sub Total&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///     {0}
        ///  &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string PO_Body_Footer {
            get {
                return ResourceManager.GetString("PO Body Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; El dia  {0}  ud {1} genero un pedido satisfactoriamente con un monto facturado de {2}. Le informaremos a la brevedad en cuanto su pedido este listo para retirar de la farmacia  {3}   &lt;p&gt;  .
        /// </summary>
        internal static string PO_Body_Header {
            get {
                return ResourceManager.GetString("PO Body Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Pedido N°  {1} generado satisfactoriamente.
        /// </summary>
        internal static string PO_Subject {
            get {
                return ResourceManager.GetString("PO Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme su correo electrónico 
        /// &lt;h1&gt; Bienvenido a {0} &lt;/h1&gt;
        /// &lt;p&gt; Confirme su correo electrónico &lt;a href=&apos;{1}&apos;&gt; Haciendo clic aquí &lt;/a&gt; &lt;/p&gt;.
        /// </summary>
        internal static string Reset_Password_body {
            get {
                return ResourceManager.GetString("Reset Password body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetear contraseña.
        /// </summary>
        internal static string Reset_Password_subject {
            get {
                return ResourceManager.GetString("Reset Password subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La URL Resetear contraseña ha sido enviada satisfactoriamente!.
        /// </summary>
        internal static string Reset_password_URL_has_been_sent_to_the_email_successfully {
            get {
                return ResourceManager.GetString("Reset password URL has been sent to the email successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algun salió mal.
        /// </summary>
        internal static string Something_went_wrong {
            get {
                return ResourceManager.GetString("Something went wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        internal static string User_Not_Found {
            get {
                return ResourceManager.GetString("User Not Found", resourceCulture);
            }
        }
    }
}
