//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VamTech.Ecommerce.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VamTech.Ecommerce.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunas propiedades no son válidas.
        /// </summary>
        internal static string Bad_Request_Some {
            get {
                return ResourceManager.GetString("Bad Request Some", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Bienvenido a {0}&lt;/h1&gt;&lt;br&gt;
        /// &lt;p&gt;Por favor confirma tu mail  &lt;a href=&apos;{1}&apos;&gt;Haciendo clic aquí&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string Confirm_your_email_body {
            get {
                return ResourceManager.GetString("Confirm your email body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma tu email.
        /// </summary>
        internal static string Confirm_your_email_subject {
            get {
                return ResourceManager.GetString("Confirm your email subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email confirmado exitosamente!.
        /// </summary>
        internal static string Email_confirmed_successfully {
            get {
                return ResourceManager.GetString("Email confirmed successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email no pudo confirmarse.
        /// </summary>
        internal static string Email_did_not_confirm {
            get {
                return ResourceManager.GetString("Email did not confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password incorrecto.
        /// </summary>
        internal static string Invalid_Password {
            get {
                return ResourceManager.GetString("Invalid Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt; ¡Hola! Se ha notado un nuevo inicio de sesión en su cuenta &lt;/h1&gt; &lt;p&gt; Nuevo inicio de sesión en su cuenta en {0} &lt;/p&gt;.
        /// </summary>
        internal static string New_login_Body {
            get {
                return ResourceManager.GetString("New login Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo login.
        /// </summary>
        internal static string New_login_subject {
            get {
                return ResourceManager.GetString("New login subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cliente el usuario asociado con el email.
        /// </summary>
        internal static string No_cliente_associated_with_email {
            get {
                return ResourceManager.GetString("No cliente associated with email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el usuario asociado con el email.
        /// </summary>
        internal static string No_user_associated_with_email {
            get {
                return ResourceManager.GetString("No user associated with email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no coincide con su confirmacion.
        /// </summary>
        internal static string Password_doesn_t_match_its_confirmation {
            get {
                return ResourceManager.GetString("Password doesn\'t match its confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña fue reseteada correctamente.
        /// </summary>
        internal static string Password_has_been_reset_successfully {
            get {
                return ResourceManager.GetString("Password has been reset successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Producto&lt;/td&gt;
        ///    &lt;td&gt;Precio Unitario&lt;/td&gt;
        ///    &lt;td&gt;Cantidad&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///     {0}
        ///  &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string PO_Body_Detail {
            get {
                return ResourceManager.GetString("PO Body Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table&gt;
        ///  &lt;tr&gt;
        ///    &lt;td&gt;Producto&lt;/td&gt;
        ///    &lt;td&gt;Descuento&lt;/td&gt;
        ///    &lt;td&gt;Sub Total&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///     {0}
        ///  &lt;/tr&gt;
        ///&lt;/table&gt;.
        /// </summary>
        internal static string PO_Body_Footer {
            get {
                return ResourceManager.GetString("PO Body Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt; El dia  {0}  ud {1} genero un pedido satisfactoriamente con un monto facturado de {2}. Le informaremos a la brevedad en cuanto su pedido este listo para retirar de la farmacia  {3}   &lt;p&gt;  .
        /// </summary>
        internal static string PO_Body_Header {
            get {
                return ResourceManager.GetString("PO Body Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} - Pedido N°  {1} generado satisfactoriamente.
        /// </summary>
        internal static string PO_Subject {
            get {
                return ResourceManager.GetString("PO Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme su correo electrónico 
        /// &lt;h1&gt; Bienvenido a {0} &lt;/h1&gt;
        /// &lt;p&gt; Confirme su correo electrónico &lt;a href=&apos;{1}&apos;&gt; Haciendo clic aquí &lt;/a&gt; &lt;/p&gt;.
        /// </summary>
        internal static string Reset_Password_body {
            get {
                return ResourceManager.GetString("Reset Password body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resetear contraseña.
        /// </summary>
        internal static string Reset_Password_subject {
            get {
                return ResourceManager.GetString("Reset Password subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La URL Resetear contraseña ha sido enviada satisfactoriamente!.
        /// </summary>
        internal static string Reset_password_URL_has_been_sent_to_the_email_successfully {
            get {
                return ResourceManager.GetString("Reset password URL has been sent to the email successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algun salió mal.
        /// </summary>
        internal static string Something_went_wrong {
            get {
                return ResourceManager.GetString("Something went wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no encontrado.
        /// </summary>
        internal static string User_Not_Found {
            get {
                return ResourceManager.GetString("User Not Found", resourceCulture);
            }
        }
    }
}
